- hosts: localhost
#JENKINS_PORT_8080_TCP_ADDR=172.17.0.2
#JENKINS_PORT_8080_TCP_PORT=8080

  vars:
    nginx_conf_dir: "/etc/nginx"
  tasks:
    - yum: pkg=nginx state=present
      when: ansible_os_family == "RedHat"

#    - name: Suppress autostart with policy-rc.d
#      copy:
#        content="#!/bin/sh\nexit 101\n"
#        dest=/usr/sbin/policy-rc.d mode=0755 
#
    - name: add apt-key
      apt_key: url=http://nginx.org/keys/nginx_signing.key state=present
      when: ansible_os_family == "Debian"

    - name: add nginx repo
      apt_repository: repo='deb http://nginx.org/packages/debian jessie nginx' state=present update_cache=yes
      when: ansible_os_family == "Debian"

    - name: install nginx
      apt: update_cache=yes name="nginx" state=present install_recommends=no
      when: ansible_os_family == "Debian"

    - name: copy site
      copy:
         src: "{{ item }}.conf"
         dest: "{{nginx_conf_dir}}/conf.d/{{ item }}.conf"
         mode: "0644"
      with_items:
        - "kibana"

#### for defautl debian nginx container
    - name: include json format
      lineinfile: dest={{nginx_conf_dir}}/nginx.conf insertafter='http {' line="include    /etc/nginx/json.conf;"

    - name: copy json.conf
      copy:
         src: "{{ item }}.conf"
         dest: "{{nginx_conf_dir}}/{{ item }}.conf"
         mode: "0644"
      with_items:
        - "json"



#
#    - name: Remove links for sites-enabled
#      file: state=absent path={{nginx_conf_dir}}/conf.d/{{ item }}.conf
#      with_items:
#        - "default"
#

#### for defautl debian nginx container
#    - name: daemon off
#      lineinfile: dest={{nginx_conf_dir}}/nginx.conf line="daemon off;"
#
#    - name: Apply index.html from template
#      template: 
#         src: index.j2 
#         dest: /var/www/html/index.html
#         mode: "0644"
#    - name: copy site
#      copy:
#         src: "{{ item }}.conf"
#         dest: "{{nginx_conf_dir}}/sites-available/{{ item }}.conf"
#         mode: "0644"
#      with_items:
#        - "kibana"
#
#    - name: Remove links for sites-enabled
#      file: state=absent path={{nginx_conf_dir}}/sites-enabled/{{ item }}
#      with_items:
#        - "default"
#
#    - name: Create links for sites-enabled
#      file: state=link src={{nginx_conf_dir}}/sites-available/{{ item }}.conf dest={{nginx_conf_dir}}/sites-enabled/{{ item }}.conf
#      with_items:
#        - "kibana"
