---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=3600

- name: Ensure Java is installed.
  apt: "name={{ item }} state=present"
  with_items: "{{ default_packages }}"

- name: Upgrade apt
  apt: upgrade=yes
