version: '2'
# define network
networks:
  front:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
      com.docker.network.enable_ipv4: "true"
    ipam:
      driver: default
      config:
      - subnet: 192.168.0.0/24
#
# define services
services:
 ctx:
  image: debian-ssh:latest
#  image: debian/jessie:latest
#  entrypoint: /sbin/init
  expose:
    - "22"
  environment:
    - SSH_KEY
  networks:
    - front
#  networks:
#      default:
#        ipv4_address: 172.18.2.2
