version: '2'
# define network
networks:
  front:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
      com.docker.network.enable_ipv4: "true"
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.0/16
  back:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
      com.docker.network.enable_ipv4: "true"
    ipam:
      driver: default
      config:
      - subnet: 172.19.0.0/16

#
# define services
services:
 ctx:
  image: debian-ssh:latest
  expose:
    - "22"
  environment:
    - SSH_KEY
  networks:
    - front
 ctb:
  image: debian-ssh:latest
  expose:
    - "22"
  environment:
    - SSH_KEY
  networks:
    - back

#  networks:
#      default:
#        ipv4_address: 172.18.2.2
