rabbitmq:
  image: dockerfile/rabbitmq
  expose:
    - "5672"
    - "15672"

jenkins:
  image: jenkins:latest
  links:
    - rabbitmq
  environment:
    JAVA_OPTS: "-Djava.awt.headless=true"
    JENKINS_OPTS: "--prefix=/jenkins"
  expose:
    - "8080"
    - "50000"

elk:
  image: elk:latest
  links:
    - rabbitmq
  expose:
    - "5601"
    - "9200"
    - "5044"
    - "5000"

web:
  image: nginx:latest
  links:
    - rabbitmq
    - jenkins
    - elk
  ports:
    - "80:80"
