---
# Variables in this file are automatically included into the role's context,
# and can be overridden by the active play.
# (Other files in this directory must be included via an `include_vars` task.)

jenkins_users_api_token:
  - builder
  - deployer
# Jenkins doesn't (and shouldn't) run as root, so this must be over 1024.
jenkins_port: 8080

# The context path that Jenkins will be hosted at, e.g. '/foo' in 
# 'http://localhost:8080/foo'. Leave as '' to host at root path.
jenkins_context_path: '/jenkins'

# The list of possible Jenkins admin users (and their security realm). At 
# Jenkins startup, the current security realm will be checked, and the first 
# user in this list that is found to match that security realm will have their 
# SSH key set to allow SSH/CLI logins using the primary SSH key of the server's
# `jenkins` system user account. Any other Jenkins users with that SSH key set 
# will have it removed, to prevent lookup conflicts.
# If you're using an alternative authorization system (i.e. security realm),
# this list will likely need to be modified to include the user ID of one of a
# valid user from that realm (unless it also happens to have an `admin` 
# account).
jenkins_admin_users:
  - 'hudson.security.HudsonPrivateSecurityRealm:admin'

# jenkins, ldap, pam
#jenkins_security_realm: 'jenkins'
#jenkins_security_realm: 'ldap'
jenkins_security_realm: 'pam'
#jenkins_authorization_strategy: unsecured, full, role,
jenkins_authorization_strategy: 'full'
#jenkins_authorization_strategy: 'unsecured'
jenkins:
  email:

# The plugins that the Jenkins 2.0 setup wizard installs by default. Currently, 
# the best place to find this list seems to be in the source, here:
# ttps://github.com/jenkinsci/jenkins/blob/master/war/src/main/js/api/plugins.js
jenkins_plugins_recommended: 
  - role-strategy
  - email-ext
  - mask-passwords
  - audit-trail
  - build-pipeline-plugin
  - copy-project-link
  - delivery-pipeline-plugin
  - git
  - git-client
  - greenballs
  - jobConfigHistory
  - jobcopy-builder
  - jquery
  - mapdb-api
  - multiple-scms
  - packer
  - parameterized-trigger
  - scm-api
  - build-timeout
  - credentials-binding
  - gradle
  - ldap
  - mailer
  - matrix-auth
  - pam-auth
  - ssh-slaves
  - skip-certificate-check
  - timestamper
  - ws-cleanup
  - urltrigger
  - ansicolor
  - ansible
  - log-parser

# The additional plugins that users of this role would like to be installed 
# (must be overridden).
jenkins_plugins_extra: []

jenkins_proxy_host: "localhost"
jenkins_proxy_port: "8888"
jenkins_num_executors: 3
