---
# This file is not included by default. It can be included via a task:
# include: "packages_{{ ansible_os_family }}.yml"

##
# FIXME: Once Jenkins 2.0 is released, install all of this via their APT repo.
# 
# That will also install the dependencies automagically.
##

- name: Update APT Cache
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: Install OS Dependencies
  apt: name={{ item }} state=installed
  become: true
  with_items:
    # The uri module requires httplib2, prior to Ansible 2.1.
    - python-httplib2
    # Allows running tasks as unprivileged users, which we need to do when running Jenkins CLI.
    # Reference: https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user
    - acl

- name: Jenkins APT Key
  apt_key:
    url: "http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key"
    state: present
  become: true

- name: Jenkins APT Repository
  apt_repository:
    repo: "deb http://pkg.jenkins-ci.org/debian binary/"
    state: present
    update_cache: yes
  become: true

- name: Jenkins Install
  apt:
    name: jenkins
    # Setting this to 'latest' is perhaps debatable, but it seems silly not to
    # since this plugin also updates all of the Jenkins plugins automatically.
    state: latest
  become: true
